# Generated by Django 3.2 on 2024-12-20 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_auto_20241208_2222'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Customer Accounts', 'verbose_name_plural': 'Cutomer Accounts'},
        ),
    ]
