# Generated by Django 3.2 on 2024-12-18 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_reply'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
