# Generated by Django 3.2 on 2024-12-15 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_alter_orderitem_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Awaiting Delivery', 'Awaiting Delivery'), ('Received', 'Received'), ('Processed', 'Processed'), ('Completed', 'Completed'), ('Expired', 'Expired'), ('Problem', 'Problem'), ('Quarantined', 'Quarantined'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Returned', 'Returned'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
