# Generated by Django 3.2 on 2024-12-16 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='postage_option',
            field=models.CharField(choices=[('paid_by_sender', 'Postage Paid by Sender'), ('prepaid', 'Prepaid Postage')], default='paid_by_sender', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='prepaid_label_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='return_tracking_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
