# Generated by Django 3.2 on 2024-12-16 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0007_auto_20241216_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='postage_option',
            field=models.CharField(choices=[('paid_by_sender', 'Postage Paid by Sender'), ('prepaid', 'Prepaid Postage')], default='', max_length=20),
        ),
    ]
