# Generated by Django 3.2 on 2024-12-18 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0009_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='revised_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='user_response',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], default='Pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Awaiting Delivery', 'Awaiting Delivery'), ('Received', 'Received'), ('Processed', 'Processed'), ('Completed', 'Completed'), ('Expired', 'Expired'), ('Problem', 'Problem'), ('Quarantined', 'Quarantined'), ('Returned', 'Returned'), ('Cancelled', 'Cancelled')], default='Awaiting Delivery', max_length=20),
        ),
    ]
