# Generated by Django 3.2 on 2024-12-18 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0010_auto_20241218_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='revised_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
