# Generated by Django 3.2 on 2024-12-18 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0012_alter_order_user_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='storage_size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
