# Generated by Django 3.2 on 2024-12-18 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0013_orderitem_storage_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='network',
            new_name='network_status',
        ),
    ]
