# Generated by Django 3.2 on 2024-12-18 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0014_rename_network_orderitem_network_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='network_status',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='network',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
