# Generated by Django 3.2 on 2024-12-19 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0015_auto_20241218_2356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='prepaid_label_url',
        ),
        migrations.RemoveField(
            model_name='order',
            name='return_tracking_code',
        ),
    ]
