# Generated by Django 3.2 on 2025-01-20 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0017_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='prepaid_label_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='return_tracking_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
