# Generated by Django 3.2 on 2025-01-21 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0018_auto_20250120_1414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='return_tracking_code',
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
