# Generated by Django 3.2 on 2024-12-15 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_mode', models.BooleanField(default=False, help_text='Toggle to enable or disable maintenance mode.')),
                ('maintenance_message', models.CharField(default='The site is currently undergoing maintenance. Please check back later.', help_text='Message to display during maintenance mode.', max_length=255)),
            ],
            options={
                'verbose_name': 'Global Setting',
                'verbose_name_plural': 'Global Settings',
            },
        ),
    ]
