# Generated by Django 3.2 on 2024-11-27 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revieworder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='network',
            field=models.CharField(blank=True, default='unlocked', max_length=50, null=True),
        ),
    ]
