# Generated by Django 3.2 on 2024-12-18 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('revieworder', '0003_cart_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='network',
            new_name='network_status',
        ),
    ]
