# Generated by Django 3.2 on 2024-12-15 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_templates', '0002_alter_emailtemplate_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='order_status',
            field=models.CharField(choices=[('Awaiting Delivery', 'Awaiting Delivery'), ('Received', 'Received'), ('Processed', 'Processed'), ('Completed', 'Completed'), ('Expired', 'Expired'), ('Problem', 'Problem'), ('Quarantined', 'Quarantined'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Returned', 'Returned'), ('Cancelled', 'Cancelled')], max_length=20),
        ),
    ]
