# Generated by Django 3.2 on 2024-12-18 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_templates', '0003_alter_emailtemplate_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='order_status',
            field=models.CharField(max_length=20),
        ),
    ]
