# Generated by Django 3.2 on 2025-01-23 17:24

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_templates', '0007_alter_emailtemplate_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailtemplate',
            name='body',
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
