# Generated by Django 3.2 on 2024-12-12 18:26

import ckeditor.fields
from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, help_text="A URL-friendly version of the brand name, used for linking to the brand's page.", null=True, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='brands/')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/')),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='ModelType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StorageOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=50)),
                ('additional_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('working_price', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True)),
                ('faulty_price', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True)),
                ('working_description', ckeditor.fields.RichTextField(blank=True, help_text='Description for working condition - Use <code>class="no-bullets"</code> in your <ul> tags to remove bullet points', null=True)),
                ('faulty_description', ckeditor.fields.RichTextField(blank=True, help_text='Description for faulty condition - Use <code>class="no-bullets"</code> in your <ul> tags to remove bullet points', null=True)),
                ('unlocked_price_adjustment', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('ee_price_adjustment', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('o2_price_adjustment', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('vodafone_price_adjustment', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('three_price_adjustment', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category')),
                ('storage_options', models.ManyToManyField(blank=True, related_name='products', to='products.StorageOption')),
            ],
        ),
        migrations.AddField(
            model_name='brand',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.category'),
        ),
    ]
