# Generated by Django 3.2 on 2024-11-07 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_brand_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='conditions',
        ),
        migrations.AddField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('working', 'Working'), ('faulty', 'Faulty')], default='working', max_length=10),
        ),
    ]
