# Generated by Django 3.2 on 2024-11-07 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20241107_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('working', 'Working'), ('faulty', 'Faulty')], default='working', max_length=20),
        ),
    ]
