# Generated by Django 3.2 on 2024-11-08 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20241108_0109'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='faulty_description',
            field=models.TextField(blank=True, help_text='Description for faulty condition', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='working_description',
            field=models.TextField(blank=True, help_text='Description for working condition', null=True),
        ),
    ]
