# Generated by Django 3.2 on 2024-11-10 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_auto_20241110_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='model_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.modeltype'),
        ),
    ]
