# Generated by Django 3.2 on 2024-11-10 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_product_model_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='model_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.modeltype'),
        ),
    ]
