# Generated by Django 3.2 on 2024-11-15 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_remove_product_model_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='category',
        ),
    ]
